import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

import '../model/vlm_response.dart';

/// The short sounds of Section 13, each with its own pitch shape.
/// Files are generated by `tool/make_earcons.py`.
enum Earcon {
  listen('listen', 20),
  read('read', 260),
  think('think', 200),
  cantSee('cant_see', 290),
  clarify('clarify', 220),
  watchPulse('watch_pulse', 70),
  error('error', 260);

  const Earcon(this.file, this.durationMs);

  final String file;
  final int durationMs;

  /// The earcon that announces a confidence level.
  static Earcon forConfidence(Confidence? c) => switch (c) {
    Confidence.read => read,
    Confidence.think => think,
    Confidence.cantSee => cantSee,
    null => think,
  };
}

/// Plays earcons with low latency. Uses an audio session that mixes with
/// speech, so earcons never cut off text-to-speech or the microphone.
class EarconPlayer {
  final Map<Earcon, AudioPlayer> _players = {};
  bool _configured = false;

  Future<void> _configure() async {
    if (_configured) return;
    _configured = true;
    try {
      await AudioPlayer.global.setAudioContext(
        AudioContext(
          iOS: AudioContextIOS(
            category: AVAudioSessionCategory.playAndRecord,
            options: const {
              AVAudioSessionOptions.defaultToSpeaker,
              AVAudioSessionOptions.mixWithOthers,
              AVAudioSessionOptions.allowBluetooth,
              AVAudioSessionOptions.allowBluetoothA2DP,
            },
          ),
          android: const AudioContextAndroid(
            contentType: AndroidContentType.sonification,
            usageType: AndroidUsageType.assistanceSonification,
            audioFocus: AndroidAudioFocus.none,
          ),
        ),
      );
    } catch (e) {
      debugPrint('[earcon] audio context not set: $e');
    }
  }

  /// Plays [e] and completes when it has finished. Does nothing if
  /// [enabled] is false. Never throws.
  Future<void> play(Earcon e, {required bool enabled}) async {
    if (!enabled) return;
    try {
      await _configure();
      final player = _players[e] ??= AudioPlayer();
      await player.play(
        AssetSource('sounds/${e.file}.wav'),
        mode: PlayerMode.lowLatency,
      );
      await Future<void>.delayed(Duration(milliseconds: e.durationMs));
    } catch (err) {
      debugPrint('[earcon] ${e.name} failed: $err');
    }
  }

  Future<void> dispose() async {
    for (final p in _players.values) {
      await p.dispose();
    }
  }
}
